In [161]:
from nltk.tokenize import word_tokenize,sent_tokenize
from nltk.corpus import stopwords
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder

In [162]:
#import nltk
#nltk.download('stopwords')

In [163]:
txt="""A hint of controversy as we wrap up the coverage of the 3rd T20I. Was Rohit declared retired out / retired hurt.

"""

In [164]:
len(txt)

114

In [165]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [166]:
len(stopwords.words('english'))

179

In [167]:
#Removing stop words
words=[]
for word in word_tokenize(txt):
    if (word.lower() not in stopwords.words('english') and len(word)>1):
        words.append(word.lower())

In [168]:
len(words)

11

In [169]:
vocab=list(set(words))

In [170]:
len(vocab)

10

### Creating encoder and decoder 

In [171]:
num=1
word_to_num={}
num_to_word={}
for word in vocab:
    word_to_num[word]=num
    num_to_word[num]=word
    num+=1

In [172]:
word_to_num

{'retired': 1,
 'rohit': 2,
 't20i': 3,
 'controversy': 4,
 'coverage': 5,
 'hint': 6,
 'declared': 7,
 'wrap': 8,
 'hurt': 9,
 '3rd': 10}

In [173]:
num_to_word[5]

'coverage'

### Encoding Sentences

In [174]:
sents=[]
for sent in sent_tokenize(txt):
    print(sent)
    sents.append(sent)

A hint of controversy as we wrap up the coverage of the 3rd T20I.
Was Rohit declared retired out / retired hurt.


In [175]:
sentences=[]
for sent in sent_tokenize(txt):
    sentence=[]
    for word in word_tokenize(sent):
        if (word.lower() not in stopwords.words('english') and len(word)>1):
            sentence.append(word)
    print(sentence)
    sentences.append(sentence[:5])
sentences

['hint', 'controversy', 'wrap', 'coverage', '3rd', 'T20I']
['Rohit', 'declared', 'retired', 'retired', 'hurt']


[['hint', 'controversy', 'wrap', 'coverage', '3rd'],
 ['Rohit', 'declared', 'retired', 'retired', 'hurt']]

### One hot encoding

In [176]:
print(pd.get_dummies(sentences[0]))

     3rd  controversy  coverage   hint   wrap
0  False        False     False   True  False
1  False         True     False  False  False
2  False        False     False  False   True
3  False        False      True  False  False
4   True        False     False  False  False


In [177]:
sents

['A hint of controversy as we wrap up the coverage of the 3rd T20I.',
 'Was Rohit declared retired out / retired hurt.']

In [178]:
sents=np.array(sents).reshape(-1, 1)
sents

array([['A hint of controversy as we wrap up the coverage of the 3rd T20I.'],
       ['Was Rohit declared retired out / retired hurt.']], dtype='<U65')

In [179]:
encoder=OneHotEncoder()

In [180]:
encoder.fit(sents)

OneHotEncoder()

In [181]:
encoded=encoder.transform(sents)
encoded

<2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [182]:
print(encoded.toarray())

[[1. 0.]
 [0. 1.]]


In [183]:
encoder.get_feature_names_out()

array(['x0_A hint of controversy as we wrap up the coverage of the 3rd T20I.',
       'x0_Was Rohit declared retired out / retired hurt.'], dtype=object)

In [184]:
sentences=np.array(sentences)

In [187]:
encoder.fit(sentences)
encoded=encoder.transform(sentences)
print(encoded.toarray())

[[0. 1. 1. 0. 0. 1. 1. 0. 1. 0.]
 [1. 0. 0. 1. 1. 0. 0. 1. 0. 1.]]
